# Generated by Django 4.2.16 on 2024-11-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('mailuser', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=30)),
                ('author_book', models.CharField(max_length=30)),
                ('publis_date', models.DateField(verbose_name='date of publication')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('borrowed_book', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='books.usersbooks')),
            ],
        ),
    ]
