# Generated by Django 4.2.16 on 2024-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookanduser_usersbooks_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbooks',
            name='books',
            field=models.ManyToManyField(null=True, related_name='borrowers', through='books.BookAndUser', to='books.book'),
        ),
    ]
