# Generated by Django 4.2.16 on 2024-12-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_usersbooks_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(verbose_name='Дата получения пользователем')),
                ('end_date', models.DateField(verbose_name='Дата возврата пользователем')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_books', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_books', to='books.usersbooks')),
            ],
        ),
    ]
